[package]
name = "fred-cal"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
fast-dav-rs.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
